#!/bin/bash

typeset -i min=$-1
typeset -i max=$2


echo -e  time in seconds
echo -e "n\tFibS(n) FibD(n)"
echo -e "-\t------- ------"

while [ $min -le $max ]
do
	beS=$(date +%s%N)
	fibS=$(./FibS $min)
	afS=$(date +%s%N)
	timeS=$(($(($afS-$beS))/1000000))
	beD=$(date +%s%N)
	fibD=$(./FibD $min)
	afD=$(date +%s%N)
	timeD=$(($(($afD-$beD))/1000000))

	echo -e "$min\t$timeS ms\t$timeD ms"
	min=$(($min+1))
done
