#!/bin/bash

typeset -i val=0


Fib()
{
	typeset -i n=$1

	if [ $n -eq 0 ]
	then
		echo 0
	elif [ $n -eq 1 ]
	then
		echo 1
	else
		typeset -i first=$(($n-1))
		typeset -i second=$(($n-2))

		typeset -i valFirst=$(Fib $first)
		typeset -i valSecond=$(Fib $second)

		val=$(($valFirst+$valSecond))

		echo $val
	fi
}

echo $(Fib $1)

