#!/bin/bash
  
typeset -i argFirst=$1
typeset -i argSecond=$2

echo "time in seconds"
echo n    FiibS\(n\)     FibD\(n\)
echo -    ---------     ---------

while [ $argFirst -le $argSecond ]
do
        beforeS=$(date +%s%N)
        callS=$(./FibS $argFirst)
        afterS=$(($(date +%s%N)-$beforeS))
        timeFibS=$(($afterS/1000000))

        beforeD=$(date +%s%N)
        callD=$(./FibD $argFirst)
        afterD=$(($(date +%s%N)-$beforeD))
        timeFibD=$(($afterD/1000000))

        echo $argFirst    $timeFibS    $timeFibD
        argFirst=$(($argFirst+1))
done
